apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-gettingstarted-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: node-gettingstarted
  replicas: 3
  template:
    metadata:
      labels:
        app: node-gettingstarted
    spec:
      containers:
        - name: node-gettingstarted
          image: vcp.ocir.io/id3kyspkytmr/node-express-getting-started:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      imagePullSecrets:
      - name: ocisecret
---
apiVersion: v1
kind: Service
metadata:
  name: node-gettingstarted-service
  namespace: default
  annotations: 
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: node-gettingstarted
